In [11]:
import numpy as np 


list = [1,2,3,4,5]
    
arr = np.array(list)
print(type(arr))
arr

# all operations of numpy in arrys only

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [14]:
np.arange(0,10)


# create array to the range 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.zeros(5)

# generate zeros array

array([0., 0., 0., 0., 0.])

In [52]:
np.zeros((3,4))

# create zeros matrix array
# (3,4) first 3 is row and 3 is column

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((5,2))

# create ones matrix array


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
rand = np.random.randint(0,10)
print(rand)

# Generate random number till range we given

9


In [37]:
np.random.randint(0,10,(3,4))

# we can generate array matrix of random number 

array([[6, 3, 7, 1],
       [3, 6, 9, 9],
       [9, 7, 5, 8]])

In [139]:
np.random.seed(1)
arr = np.random.randint(0,100,10)

print(arr)

print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.argmax(arr)) #give max number index
print(np.argmin(arr)) #give min number index

# when we want random number array to take constant output then we use seed
#101 is any parameter

[37 12 72  9 75  5 79 64 16  1]
79
1
37.0
6
9


In [195]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [211]:
mat[0,1]

mat[::]
mat[1,:] #row
mat[:,2] #column
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])